## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function
#
# This makeCacheMatrix function takes an invertible matrix as input and generates its inverse
# that is held in cache. The function contains subfunctions callable from its parent environment to 1) 
# show the given matrix (get), 2) input a new matrix(set), call solve() to calulate the inverse
# matrix (setenv), and 4) retrieve the inverse matrix (setenv). The function will send a message
# that the  output a previously cached inverse matrix. The <<- assignment operator is used to assign values 
# found within the parent environment.
#
makeCacheMatrix <- function(mtx = matrix()) {
        if(!is.matrix(mtx)) stop("input must be a matrix")
        inv_mtx <- NULL
        set <- function(y) {
                mtx <<- y
                inv_mtx <<- NULL
        }
        get <- function() mtx 
        getinv <- function() inv_mtx
        setinv <- function() inv_mtx <<- solve(mtx)
        list(get = get, set = set, getinv = getinv,setinv = setinv)
}        
#
# This cacheSolve function returns the inverse matrix generated by calling subfunctions found in the 
# makeCacheMatrix function described above. The function will first check to see if the matrix has already been cached
# before making the function calls necessary to generate a new matrix. A message will be printed if previously cached data
# is being returned.
#
cacheSolve <- function(f_mtx, ...){
        inv_mtx <- f_mtx$getinv()
        if(!is.null(inv_mtx)){
                message("retrieving cached data")
                return(inv_mtx)
        } 
        mtx <- f_mtx$get()
        inv_mtx <-f_mtx$setinv()
        return(inv_mtx)
}
